management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: techtask
  datasource:
    driver-Class-Name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 30000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true



security:
  jwt:
    secret: c2pkZmdranNscnRwZmdzZGtmZ2psc2tyanRbcGZnZGZrZ2xqZWxrcmpwb2dpcHNka2dhbHNramR0bGtqbGtqZ2xkZmdzcnRlcw==
    access: 3600000
    refresh: 2592000000

springdoc:
  override-with-generic-response: false