management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: techtask
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-Class-Name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}


security:
  jwt:
    secret: ${JWT_SECRET}
    access: 3600000     #1hour
    refresh: 2592000000 #30days

springdoc:
  override-with-generic-response: false

minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin